### ISSUE TITLE
Issue when training on WILDS

### ISSUE THREAD

**Issue by saraalemadi** [cianeastwood/qrm#1]
Hi @arobey1

I am trying to replicate your experiment on WILDS suite but I am getting the following error:

```
Train:
Traceback (most recent call last):
  File "wilds/examples/run_expt.py", line 490, in <module>
    main()
  File "wilds/examples/run_expt.py", line 453, in main
    train(
  File "wilds/examples/train.py", line 114, in train
    run_epoch(algorithm, datasets['train_n'], general_logger, epoch, config, train=True, unlabeled_dataset=unlabeled_dataset)
  File "wilds/examples/train.py", line 48, in run_epoch
    batch_results = algorithm.update(labeled_batch, is_epoch_end=(batch_idx==last_batch_idx))
  File "wilds/examples/algorithms/single_model_algorithm.py", line 142, in update
    self._update(
  File "wilds/examples/algorithms/single_model_algorithm.py", line 164, in _update
    objective = self.objective(results)
  File "wilds/examples/algorithms/QRM.py", line 36, in objective
    obj = self.dist.icdf(self.q)
  File "wilds/examples/algorithms/QRM.py", line 280, in icdf
    return super().icdf(q)
  File "wilds/examples/algorithms/QRM.py", line 199, in icdf
    return self.create_dist().icdf(q)
  File "wilds/examples/algorithms/QRM.py", line 185, in create_dist
    return self.dist_function(*self.parameters)
  File "/anaconda3/envs/wilds/lib/python3.10/site-packages/torch/distributions/normal.py", line 54, in __init__
    super(Normal, self).__init__(batch_shape, validate_args=validate_args)
  File "anaconda3/envs/wilds/lib/python3.10/site-packages/torch/distributions/distribution.py", line 55, in __init__
    raise ValueError(
ValueError: Expected parameter scale (Tensor of shape ()) of distribution Normal(loc: 4.2827582359313965, scale: nan) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
nan
```

**Comment by Anurag14** [comment]
Hi @cianeastwood, I was wondering if there is some way to resolve this issue. Is it due to the different seeds used in experiment?  

I am also trying to reproduce the same experiment, however, for both QRM_KDE and QRM_normal, the parameters estimate returns nan.

**Comment by cianeastwood** [comment]
Hi @Anurag14 , I don't currently have the capacity to run the WILDS experiments, but this error is likely coming from one of two lines:

- [Line 274:](https://github.com/cianeastwood/qrm/blob/6c216fa73d9ad71ea02d866be4b01eacaab348db/WILDS/examples/algorithms/QRM.py#L274) Try printing this to ensure it's never nan (e.g., if there's only 1 environment, this may need some edge-case protection/updates).
- [Line 276:](https://github.com/cianeastwood/qrm/blob/6c216fa73d9ad71ea02d866be4b01eacaab348db/WILDS/examples/algorithms/QRM.py#L276) Try increasing EPS to ensure the variance is always positive (non-zero).

**Comment by cianeastwood** [comment]
@Anurag14 -- please let me know if you resolve it (or, in an ideal world, submit a pull request! :) )

**Comment by Anurag14** [comment]
Hi @cianeastwood, Thanks for the fix <3, I only tried reproducing the results. The fix worked in my case. I am not actively using the codebase for WILDS as part of my projects. In case I use it in future and come up with another fix, I will put a pull request!

**Comment by cianeastwood** [comment]
What was the fix -- line 274 or 276 (in the comment above)?

**Comment by Anurag14** [comment]
As far as I can recall to the best of my understanding,  it was caused by config. [Line 249](https://github.com/cianeastwood/qrm/blob/6c216fa73d9ad71ea02d866be4b01eacaab348db/WILDS/examples/configs/datasets.py#L249C9-L249C33). Where number of groups per batch is 2. I assume this was causing the variance to be poorly estimated in a batch. Increasing this config worked afaik, but I haven't worked on the codebase since long time. 

Regardless for future reference if we want to run on very few environments clamping the variance should work. 
Probably something like this for Line 247

 `var = min(sum([(x_i - mean) ** 2 for x_i in x]) / (len(x) - 1),1e7)`

**Comment by cianeastwood** [comment]
Looks like EPS just needed to be increased for this few/two-environment case -- now resolved
